import 'dart:convert';
import 'package:http/http.dart' as http;

import '../config/api.dart';

class ProblemSetApi {
  /// ✅ (구버전) problemSetId만 받아서 Commit
  static Future<void> commitProblemSet({
    required int problemSetId,
  }) async {
    final url = ApiConfig.u('/problem-sets/auto-generate/commit');

    final res = await http.post(
      url,
      headers: const {'Content-Type': 'application/json'},
      body: jsonEncode({
        'problem_set_id': problemSetId,
      }),
    );

    if (res.statusCode != 200) {
      throw Exception('Commit 실패: ${res.statusCode} ${res.body}');
    }
  }

  /// ✅ Step 3-4-5
  /// 자동 생성된 시험지 Commit (analysis 기반)
  static Future<int> commitAutoGeneratedProblemSet({
    required int analysisId,
    required String name,
    required int totalQuestions,
    required Map<String, double> distribution,
    String mode = 'teacher',
  }) async {
    final url = ApiConfig.u('/problem-sets/auto-generate/commit');

    final payload = {
      'analysis_id': analysisId,
      'name': name,
      'total_questions': totalQuestions,
      'distribution': distribution,
      'mode': mode,
    };

    final res = await http.post(
      url,
      headers: const {'Content-Type': 'application/json'},
      body: jsonEncode(payload),
    );

    if (res.statusCode != 200) {
      throw Exception('Commit 실패: ${res.body}');
    }

    final decoded = jsonDecode(res.body);
    return decoded['problem_set_id'] as int;
  }
}
