// lib/services/teacher_api.dart
import 'dart:convert';
import 'package:http/http.dart' as http;

import '../config/api.dart';

/// 선생님용 API 모음
class TeacherApi {
  /// GPT 자동 생성 세트를 **바로 DB에 저장**하고 problem_set_id 받기
  static Future<int> saveAutoGeneratedSet({
    required String passageContent,
    String? passageTitle,
    required int numQuestions,
    String?
        questionType, // 'topic' / 'title' / 'gist' / 'summary' / 'cloze' / 'insertion' / 'order' / 'all'
  }) async {
    // FastAPI 백엔드 /teacher/question-sets
    final uri = ApiConfig.u('${ApiConfig.baseUrl}/teacher/question-sets');

    final bodyMap = <String, dynamic>{
      'passage_title': passageTitle ?? '자동 생성 지문',
      'passage_content': passageContent,
      'num_questions': numQuestions,
      'problem_set_name': '자동 생성 세트',
      'description': null,
      // 질문 배열 비워서 보내면 백엔드가 내부에서 GPT 호출
      'questions': <dynamic>[],
      // question_type 이 null 이 아니고 'all' 이 아니면 같이 전송
      if (questionType != null && questionType != 'all')
        'question_type': questionType,
    };

    final resp = await http.post(
      uri,
      headers: const {'Content-Type': 'application/json'},
      body: jsonEncode(bodyMap),
    );

    if (resp.statusCode != 200 && resp.statusCode != 201) {
      throw Exception(
        '자동 생성 세트 저장 실패: ${resp.statusCode} / ${resp.body}',
      );
    }

    final data = jsonDecode(resp.body) as Map<String, dynamic>;
    final problemSetId = data['problem_set_id'];

    if (problemSetId is! int) {
      throw Exception('응답에 problem_set_id가 없습니다: $data');
    }

    return problemSetId;
  }
}
