// lib/services/teacher_api.dart
import 'dart:convert';
import 'package:http/http.dart' as http;

import '../config/api.dart';

/// 선생님 관련 API 호출 모음
class TeacherApi {
  /// 🔹 지문 + 자동 생성 문항 수를 보내서
  ///    백엔드(/teacher/question-sets)가 GPT로 문제를 만들고
  ///    DB에 저장한 뒤, 생성된 problem_set_id를 돌려준다.
  ///
  /// 반환값: 저장된 ProblemSet의 ID (학생 모드에서 바로 사용)
  static Future<int> saveAutoGeneratedSet({
    required String passageContent,
    String? passageTitle,
    int numQuestions = 1,
  }) async {
    // 1) URL 만들기 (ApiConfig 사용)
    final uri = ApiConfig.u(ApiConfig.teacherQuestionSets);

    // 2) 요청 바디
    final bodyMap = <String, dynamic>{
      'passage_title': passageTitle ?? '',
      'passage_content': passageContent,
      'problem_set_name': '자동 생성 세트',
      'description': '자동 생성 문제 세트',
      'num_questions': numQuestions,
      // questions 를 비워 두면 백엔드에서 GPT로 자동 생성
      'questions': [],
    };

    // 3) POST 전송
    final resp = await http.post(
      uri,
      headers: const {'Content-Type': 'application/json'},
      body: jsonEncode(bodyMap),
    );

    if (resp.statusCode != 200 && resp.statusCode != 201) {
      throw Exception(
        '자동 생성 세트 저장 실패: ${resp.statusCode} / ${resp.body}',
      );
    }

    // 4) 응답 파싱
    final data = jsonDecode(resp.body) as Map<String, dynamic>;

    // 백엔드에서 내려주는 필드 이름: problem_set_id
    final problemSetId = data['problem_set_id'];
    if (problemSetId is! int) {
      throw Exception('응답에 problem_set_id가 없습니다: $data');
    }

    return problemSetId;
  }
}
