// lib/screens/teacher_question_maker_screen.dart
import 'package:flutter/material.dart';
import '../config/api.dart';
import '../services/teacher_api.dart'; // 이전에 만들었던 API 서비스

/// 문제 유형 키
enum QuestionTypeKey {
  topic, // 주제
  title, // 제목
  gist, // 요지
  summary, // 요약
  cloze, // 빈칸
  insertion, // 삽입
  order, // 순서
  all, // 전체(모든 유형)
}

class TeacherQuestionMakerScreen extends StatefulWidget {
  const TeacherQuestionMakerScreen({super.key});

  @override
  State<TeacherQuestionMakerScreen> createState() =>
      _TeacherQuestionMakerScreenState();
}

class _TeacherQuestionMakerScreenState
    extends State<TeacherQuestionMakerScreen> {
  // 지문 제목은 이제 안 쓰지만, 혹시 모를 확장을 위해 남겨둠
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _passageController = TextEditingController();

  QuestionTypeKey _selectedType = QuestionTypeKey.all;
  int _numQuestions = 1;
  bool _isLoading = false;

  // ---------- Helper: 유형 한글 라벨 ----------
  String _labelForType(QuestionTypeKey type) {
    switch (type) {
      case QuestionTypeKey.topic:
        return '주제';
      case QuestionTypeKey.title:
        return '제목';
      case QuestionTypeKey.gist:
        return '요지';
      case QuestionTypeKey.summary:
        return '요약';
      case QuestionTypeKey.cloze:
        return '빈칸';
      case QuestionTypeKey.insertion:
        return '삽입';
      case QuestionTypeKey.order:
        return '순서';
      case QuestionTypeKey.all:
        return '전체 (모든 유형)';
    }
  }

  // 나중에 백엔드와 연결할 때 사용할 수 있는 key
  String _typeKeyForApi(QuestionTypeKey type) {
    switch (type) {
      case QuestionTypeKey.topic:
        return 'topic';
      case QuestionTypeKey.title:
        return 'title';
      case QuestionTypeKey.gist:
        return 'gist';
      case QuestionTypeKey.summary:
        return 'summary';
      case QuestionTypeKey.cloze:
        return 'cloze';
      case QuestionTypeKey.insertion:
        return 'insertion';
      case QuestionTypeKey.order:
        return 'order';
      case QuestionTypeKey.all:
        return 'all';
    }
  }

  // ---------- 유형 선택 bottom sheet ----------
  void _showQuestionTypeSelector() {
    showModalBottomSheet<void>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (ctx) {
        return SafeArea(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const SizedBox(height: 12),
              Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.outlineVariant,
                  borderRadius: BorderRadius.circular(999),
                ),
              ),
              const SizedBox(height: 16),
              const Text(
                '문제 유형 선택',
                style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 8),
              const Divider(height: 1),
              Flexible(
                child: ListView(
                  shrinkWrap: true,
                  children: QuestionTypeKey.values.map((t) {
                    final selected = t == _selectedType;
                    return ListTile(
                      title: Text(_labelForType(t)),
                      trailing: selected
                          ? Icon(Icons.check,
                              color: Theme.of(context).colorScheme.primary)
                          : null,
                      onTap: () {
                        setState(() {
                          _selectedType = t;
                        });
                        Navigator.of(ctx).pop();
                      },
                    );
                  }).toList(),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  // ---------- 자동 생성 + 저장 + 학생모드 이동 ----------
  Future<void> _onAutoGenerateAndStart() async {
    final passage = _passageController.text.trim();
    if (passage.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('지문을 먼저 입력해 주세요.')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      // 1) 자동 생성 문제 세트 저장 (백엔드: /teacher/question-sets)
      final problemSetId = await TeacherApi.saveAutoGeneratedSet(
        passageContent: passage,
        passageTitle: _titleController.text.trim().isEmpty
            ? null
            : _titleController.text.trim(),
        numQuestions: _numQuestions,
        // 나중에 사용할 수 있도록 로그만 찍어둠
        // questionType: _typeKeyForApi(_selectedType),
      );

      // 2) 학생 모드로 이동
      if (!mounted) return;
      Navigator.of(context).pushNamed(
        '/student_quiz',
        arguments: {'problemSetId': problemSetId},
      );

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('저장 완료! problem_set_id = $problemSetId'),
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('저장 중 오류가 발생했습니다: $e')),
      );
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _passageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('문제 제작 (선생님 모드)'),
      ),
      body: Column(
        children: [
          // ---------- 1. 유형 선택 영역 ----------
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '문제 유형 선택',
                  style: theme.textTheme.labelMedium,
                ),
                const SizedBox(height: 6),
                InkWell(
                  onTap: _showQuestionTypeSelector,
                  borderRadius: BorderRadius.circular(12),
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 12, vertical: 12),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                        color: theme.colorScheme.outlineVariant,
                      ),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.tune,
                          size: 18,
                          color: theme.colorScheme.primary,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          _labelForType(_selectedType),
                          style: theme.textTheme.bodyMedium,
                        ),
                        const Spacer(),
                        const Icon(Icons.arrow_drop_down),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),

          // ---------- 2. 지문 입력 ----------
          Expanded(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(16, 8, 16, 8),
              child: TextField(
                controller: _passageController,
                maxLines: null,
                expands: true,
                keyboardType: TextInputType.multiline,
                decoration: const InputDecoration(
                  labelText: '지문 입력',
                  alignLabelWithHint: true,
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ),

          // ---------- 3. 하단 : 자동 생성 문항 수 + 버튼 ----------
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 8),
            child: Row(
              children: [
                Text(
                  '자동 생성 문항 수',
                  style: theme.textTheme.bodyMedium,
                ),
                const Spacer(),
                DropdownButton<int>(
                  value: _numQuestions,
                  items: const [
                    DropdownMenuItem(value: 1, child: Text('1개')),
                    DropdownMenuItem(value: 2, child: Text('2개')),
                    DropdownMenuItem(value: 3, child: Text('3개')),
                    DropdownMenuItem(value: 4, child: Text('4개')),
                    DropdownMenuItem(value: 5, child: Text('5개')),
                  ],
                  onChanged: (v) {
                    if (v != null) {
                      setState(() => _numQuestions = v);
                    }
                  },
                ),
              ],
            ),
          ),
          const SizedBox(height: 4),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            child: SizedBox(
              width: double.infinity,
              height: 48,
              child: FilledButton.icon(
                onPressed: _isLoading ? null : _onAutoGenerateAndStart,
                icon: _isLoading
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.auto_awesome),
                label: Text(
                  _isLoading ? '생성 중...' : '자동 생성 후 학생모드로 풀기',
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
