// lib/screens/teacher_question_maker_screen.dart
import 'package:flutter/material.dart';

import '../services/teacher_api.dart';
import 'teacher_problem_sets_screen.dart';

enum QuestionTypeKey {
  topic,
  title,
  gist,
  summary,
  cloze,
  insertion,
  order,
  all,
}

class TeacherQuestionMakerScreen extends StatefulWidget {
  const TeacherQuestionMakerScreen({super.key});

  @override
  State<TeacherQuestionMakerScreen> createState() =>
      _TeacherQuestionMakerScreenState();
}

class _TeacherQuestionMakerScreenState
    extends State<TeacherQuestionMakerScreen> {
  static const _brandBlue = Color(0xFF2563EB);
  static const _ink = Color(0xFF172033);
  static const _line = Color(0xFFE2E8F0);
  static const _surface = Color(0xFFF4F7FB);

  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _passageController = TextEditingController();

  QuestionTypeKey _selectedType = QuestionTypeKey.all;
  int _numQuestions = 1;
  bool _isLoading = false;

  String _labelForType(QuestionTypeKey type) {
    switch (type) {
      case QuestionTypeKey.topic:
        return '주제';
      case QuestionTypeKey.title:
        return '제목';
      case QuestionTypeKey.gist:
        return '요지';
      case QuestionTypeKey.summary:
        return '요약';
      case QuestionTypeKey.cloze:
        return '빈칸 추론';
      case QuestionTypeKey.insertion:
        return '문장 삽입';
      case QuestionTypeKey.order:
        return '순서 배열';
      case QuestionTypeKey.all:
        return '전체';
    }
  }

  String _typeKeyForApi(QuestionTypeKey type) {
    switch (type) {
      case QuestionTypeKey.topic:
        return 'topic';
      case QuestionTypeKey.title:
        return 'title';
      case QuestionTypeKey.gist:
        return 'gist';
      case QuestionTypeKey.summary:
        return 'summary';
      case QuestionTypeKey.cloze:
        return 'cloze';
      case QuestionTypeKey.insertion:
        return 'insertion';
      case QuestionTypeKey.order:
        return 'order';
      case QuestionTypeKey.all:
        return 'all';
    }
  }

  Future<void> _onAutoGenerateAndStart() async {
    final passage = _passageController.text.trim();
    if (passage.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('지문을 입력해 주세요.')),
      );
      return;
    }

    final questionTypeForApi = _typeKeyForApi(_selectedType);

    setState(() => _isLoading = true);

    try {
      final problemSetId = await TeacherApi.saveAutoGeneratedSet(
        passageContent: passage,
        passageTitle: _titleController.text.trim().isEmpty
            ? null
            : _titleController.text.trim(),
        numQuestions: _numQuestions,
        questionType: questionTypeForApi,
      );

      if (!mounted) return;
      Navigator.of(context).pushNamed(
        '/student_quiz',
        arguments: {
          'problemSetId': problemSetId,
          'questionType': questionTypeForApi,
        },
      );

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('문제세트 저장 완료: $problemSetId')),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('문제 생성 중 오류가 발생했습니다: $e')),
      );
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _passageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _surface,
      appBar: AppBar(
        backgroundColor: Colors.white,
        foregroundColor: _ink,
        elevation: 0,
        surfaceTintColor: Colors.white,
        title: const Text(
          '문제 제작',
          style: TextStyle(fontWeight: FontWeight.w800),
        ),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 12),
            child: OutlinedButton.icon(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => const TeacherProblemSetsScreen(),
                  ),
                );
              },
              icon: const Icon(Icons.folder_copy_outlined, size: 18),
              label: const Text('문제세트'),
              style: OutlinedButton.styleFrom(
                foregroundColor: _brandBlue,
                side: const BorderSide(color: Color(0xFFBFDBFE)),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(18),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 1080),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const _HeaderCard(
                  icon: Icons.edit_note_outlined,
                  title: '수업 자료 기반 문제 제작',
                  subtitle: '지문을 입력하고 유형과 문항 수를 선택하면 바로 문제세트를 생성합니다.',
                ),
                const SizedBox(height: 16),
                _AdminCard(
                  child: Padding(
                    padding: const EdgeInsets.all(18),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const _SectionTitle(
                          title: '제작 설정',
                          subtitle: '출제 유형과 문항 수를 먼저 선택하세요.',
                        ),
                        const SizedBox(height: 16),
                        LayoutBuilder(
                          builder: (context, constraints) {
                            final stacked = constraints.maxWidth < 720;
                            final controls = [
                              Expanded(
                                child: _FieldShell(
                                  label: '문제 유형',
                                  child: DropdownButtonHideUnderline(
                                    child: DropdownButton<QuestionTypeKey>(
                                      value: _selectedType,
                                      isExpanded: true,
                                      icon: const Icon(Icons.expand_more),
                                      items: QuestionTypeKey.values
                                          .map(
                                            (type) => DropdownMenuItem(
                                              value: type,
                                              child: Text(_labelForType(type)),
                                            ),
                                          )
                                          .toList(),
                                      onChanged: (type) {
                                        if (type == null) return;
                                        setState(() => _selectedType = type);
                                      },
                                    ),
                                  ),
                                ),
                              ),
                              Expanded(
                                child: _FieldShell(
                                  label: '자동 생성 문항 수',
                                  child: DropdownButtonHideUnderline(
                                    child: DropdownButton<int>(
                                      value: _numQuestions,
                                      isExpanded: true,
                                      icon: const Icon(Icons.expand_more),
                                      items: const [
                                        DropdownMenuItem(
                                          value: 1,
                                          child: Text('1개'),
                                        ),
                                        DropdownMenuItem(
                                          value: 2,
                                          child: Text('2개'),
                                        ),
                                        DropdownMenuItem(
                                          value: 3,
                                          child: Text('3개'),
                                        ),
                                        DropdownMenuItem(
                                          value: 4,
                                          child: Text('4개'),
                                        ),
                                        DropdownMenuItem(
                                          value: 5,
                                          child: Text('5개'),
                                        ),
                                      ],
                                      onChanged: (value) {
                                        if (value == null) return;
                                        setState(() => _numQuestions = value);
                                      },
                                    ),
                                  ),
                                ),
                              ),
                            ];

                            if (stacked) {
                              return Column(
                                children: [
                                  controls[0],
                                  const SizedBox(height: 12),
                                  controls[1],
                                ],
                              );
                            }

                            return Row(
                              children: [
                                controls[0],
                                const SizedBox(width: 12),
                                controls[1],
                              ],
                            );
                          },
                        ),
                        const SizedBox(height: 16),
                        TextField(
                          controller: _titleController,
                          decoration: _inputDecoration(
                            label: '자료명',
                            hint: '예: 고2 5월 모의고사 빈칸 추론',
                          ),
                        ),
                        const SizedBox(height: 12),
                        TextField(
                          controller: _passageController,
                          minLines: 12,
                          maxLines: 18,
                          keyboardType: TextInputType.multiline,
                          decoration: _inputDecoration(
                            label: '지문 입력',
                            hint: '문제를 만들 영어 지문을 붙여넣으세요.',
                            alignLabelWithHint: true,
                          ),
                        ),
                        const SizedBox(height: 18),
                        SizedBox(
                          width: double.infinity,
                          height: 48,
                          child: FilledButton.icon(
                            onPressed:
                                _isLoading ? null : _onAutoGenerateAndStart,
                            icon: _isLoading
                                ? const SizedBox(
                                    width: 18,
                                    height: 18,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      color: Colors.white,
                                    ),
                                  )
                                : const Icon(Icons.auto_awesome),
                            label: Text(
                              _isLoading ? '생성 중...' : '자동 생성 후 학생모드로 풀기',
                            ),
                            style: FilledButton.styleFrom(
                              backgroundColor: _brandBlue,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(8),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  InputDecoration _inputDecoration({
    required String label,
    required String hint,
    bool alignLabelWithHint = false,
  }) {
    return InputDecoration(
      labelText: label,
      hintText: hint,
      alignLabelWithHint: alignLabelWithHint,
      filled: true,
      fillColor: const Color(0xFFF8FAFC),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: _line),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: _line),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(8),
        borderSide: const BorderSide(color: _brandBlue, width: 1.5),
      ),
    );
  }
}

class _HeaderCard extends StatelessWidget {
  const _HeaderCard({
    required this.icon,
    required this.title,
    required this.subtitle,
  });

  final IconData icon;
  final String title;
  final String subtitle;

  @override
  Widget build(BuildContext context) {
    return _AdminCard(
      child: Padding(
        padding: const EdgeInsets.all(18),
        child: Row(
          children: [
            Container(
              width: 44,
              height: 44,
              decoration: BoxDecoration(
                color: const Color(0xFFEFF6FF),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(icon, color: _TeacherColors.blue),
            ),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: const TextStyle(
                      color: _TeacherColors.ink,
                      fontSize: 18,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    subtitle,
                    style: const TextStyle(
                      color: _TeacherColors.muted,
                      fontSize: 13,
                      height: 1.45,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _SectionTitle extends StatelessWidget {
  const _SectionTitle({required this.title, required this.subtitle});

  final String title;
  final String subtitle;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            color: _TeacherColors.ink,
            fontSize: 16,
            fontWeight: FontWeight.w800,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          subtitle,
          style: const TextStyle(
            color: _TeacherColors.muted,
            fontSize: 13,
          ),
        ),
      ],
    );
  }
}

class _FieldShell extends StatelessWidget {
  const _FieldShell({required this.label, required this.child});

  final String label;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 70,
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: _TeacherColors.line),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: const TextStyle(
              color: _TeacherColors.muted,
              fontSize: 12,
              fontWeight: FontWeight.w700,
            ),
          ),
          Expanded(child: child),
        ],
      ),
    );
  }
}

class _AdminCard extends StatelessWidget {
  const _AdminCard({required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: _TeacherColors.line),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF0F172A).withValues(alpha: 0.05),
            offset: const Offset(0, 10),
            blurRadius: 24,
          ),
        ],
      ),
      child: child,
    );
  }
}

class _TeacherColors {
  static const blue = Color(0xFF2563EB);
  static const ink = Color(0xFF172033);
  static const muted = Color(0xFF64748B);
  static const line = Color(0xFFE2E8F0);
}
