import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/final_touch.dart';
import '../models/final_touch_report.dart';

class FinalTouchPdfGenerator {
  static Future<void> previewOrPrint(FinalTouchReport report) async {
    final bytes = await build(report);
    await Printing.layoutPdf(
      name: _filename(report),
      onLayout: (_) async => bytes,
    );
  }

  static Future<Uint8List> build(FinalTouchReport report) async {
    final fontData = await rootBundle.load(
      'assets/fonts/Noto_Sans_KR/NotoSansKR-VariableFont_wght.ttf',
    );
    final notoSans = pw.Font.ttf(fontData);
    final doc = pw.Document(
      theme: pw.ThemeData.withFont(base: notoSans, bold: notoSans),
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header(report),
          pw.SizedBox(height: 16),
          _coreSection(report),
          pw.SizedBox(height: 18),
          _sectionTitle('문장별 세부 분석'),
          pw.SizedBox(height: 8),
          if (report.sentenceDetails.isEmpty)
            _emptyText('표시할 문장별 세부 분석이 없습니다.')
          else
            ...report.sentenceDetails.expand(
              (detail) => [
                _sentenceDetail(detail),
                pw.SizedBox(height: 10),
              ],
            ),
          if (report.passageBracketed.trim().isNotEmpty) ...[
            pw.SizedBox(height: 10),
            _fullBracketedSection(report.passageBracketed),
          ],
          pw.SizedBox(height: 22),
          pw.Divider(color: PdfColors.grey300),
          pw.Text(
            'Generated by 영어문제제작 시스템 / messimomo',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _header(FinalTouchReport report) {
    final metadata = <String>[
      if (report.source.trim().isNotEmpty) '출처: ${report.source}',
      if (report.textbookFolder.trim().isNotEmpty)
        '교재: ${report.textbookFolder}',
      if (report.unitFolder.trim().isNotEmpty) '단원: ${report.unitFolder}',
      if (report.passageId != null) 'Passage ID: ${report.passageId}',
      '출력일: ${_formatDate(report.createdAt)}',
    ];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Final Touch 분석 리포트',
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#172033'),
          ),
        ),
        pw.SizedBox(height: 7),
        pw.Text(
          '지문의 흐름과 핵심 내용, 문장별 분석을 수업 자료로 정리했습니다.',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 10),
        pw.Wrap(
          spacing: 6,
          runSpacing: 6,
          children: metadata.map(_metadataPill).toList(),
        ),
      ],
    );
  }

  static pw.Widget _metadataPill(String text) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#F8FAFC'),
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
      ),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 8.5, color: PdfColors.grey800),
      ),
    );
  }

  static pw.Widget _coreSection(FinalTouchReport report) {
    final items = <({String label, String en, String ko})>[
      (label: '주제', en: report.topicEn, ko: report.topicKo),
      (label: '제목', en: report.titleEn, ko: report.titleKo),
      (label: '요지', en: report.gistEn, ko: report.gistKo),
      if (report.summaryEn.trim().isNotEmpty ||
          report.summaryKo.trim().isNotEmpty)
        (label: '요약', en: report.summaryEn, ko: report.summaryKo),
    ];

    return _sectionBox(
      title: '핵심 분석',
      color: '#EAF3FF',
      border: '#BBD7FF',
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: items.expand((item) {
          final isLast = item == items.last;
          return [
            _coreItem(item.label, item.en, item.ko),
            if (!isLast) ...[
              pw.SizedBox(height: 8),
              pw.Divider(color: PdfColor.fromHex('#BFDBFE')),
              pw.SizedBox(height: 8),
            ],
          ];
        }).toList(),
      ),
    );
  }

  static pw.Widget _coreItem(String label, String english, String korean) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 10,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#2563EB'),
          ),
        ),
        pw.SizedBox(height: 4),
        _languageLine('영어', english),
        pw.SizedBox(height: 4),
        _languageLine('한국어', korean),
      ],
    );
  }

  static pw.Widget _languageLine(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          '$label:',
          style: pw.TextStyle(
            fontSize: 8.8,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#475569'),
          ),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          value.trim().isEmpty ? '-' : value,
          style: pw.TextStyle(
            fontSize: 10,
            height: 1.5,
            color: PdfColor.fromHex('#111827'),
          ),
        ),
      ],
    );
  }

  static pw.Widget _sentenceDetail(FinalTouchSentenceDetail detail) {
    final bracketed =
        detail.bracketed.trim().isEmpty ? detail.original : detail.bracketed;
    final translation = detail.translation.trim().isEmpty
        ? '해석이 준비되지 않았습니다.'
        : detail.translation;

    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(color: PdfColor.fromHex('#DCE4EE')),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Container(
                width: 22,
                height: 22,
                alignment: pw.Alignment.center,
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#2563EB'),
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Text(
                  '${detail.sentenceNo}',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white,
                  ),
                ),
              ),
              pw.SizedBox(width: 7),
              pw.Text(
                detail.sentenceRole.trim().isEmpty
                    ? '문장 역할'
                    : detail.sentenceRole,
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#1D4ED8'),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 9),
          _smallLabel('영문 분석'),
          pw.SizedBox(height: 3),
          _bracketedText(
            bracketed,
            style: pw.TextStyle(
              fontSize: 10.4,
              height: 1.55,
              color: PdfColor.fromHex('#111827'),
            ),
          ),
          pw.SizedBox(height: 8),
          _smallLabel('해석'),
          pw.SizedBox(height: 3),
          pw.Text(
            translation,
            style: pw.TextStyle(
              fontSize: 9.8,
              height: 1.55,
              color: PdfColor.fromHex('#1F2937'),
            ),
          ),
          if (detail.grammarPoints.isNotEmpty) ...[
            pw.SizedBox(height: 9),
            _grammarBox(detail.grammarPoints),
          ],
          if (detail.questionPoint.trim().isNotEmpty) ...[
            pw.SizedBox(height: 9),
            _questionPointBox(detail.questionPoint),
          ],
        ],
      ),
    );
  }

  static pw.Widget _grammarBox(List<FinalTouchGrammarPoint> points) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(9),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#FEF2F2'),
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColor.fromHex('#FECACA')),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _smallLabel('문법 포인트', color: '#B91C1C'),
          pw.SizedBox(height: 5),
          ...points.expand(
            (point) => [
              pw.Text(
                '[${point.label}] ${point.target}',
                style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#7F1D1D'),
                ),
              ),
              pw.SizedBox(height: 2),
              pw.Text(
                point.explanation,
                style: pw.TextStyle(
                  fontSize: 8.8,
                  height: 1.45,
                  color: PdfColor.fromHex('#1F2937'),
                ),
              ),
              pw.SizedBox(height: 5),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _questionPointBox(String value) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(9),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#EFF6FF'),
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColor.fromHex('#93C5FD')),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _smallLabel('문제화 포인트'),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 8.5,
              height: 1.4,
              color: PdfColor.fromHex('#1F2937'),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _fullBracketedSection(String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('전체 괄호 구조 보기'),
        pw.SizedBox(height: 8),
        pw.Container(
          width: double.infinity,
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColor.fromHex('#F8FAFC'),
            borderRadius: pw.BorderRadius.circular(10),
            border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
          ),
          child: _bracketedText(
            value,
            style: pw.TextStyle(
              fontSize: 9.6,
              height: 1.6,
              color: PdfColor.fromHex('#111827'),
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _bracketedText(
    String value, {
    required pw.TextStyle style,
  }) {
    final spans = <pw.InlineSpan>[];
    var index = 0;

    while (index < value.length) {
      final next = _nextBracket(value, index);
      if (next == null) {
        spans.add(pw.TextSpan(text: value.substring(index), style: style));
        break;
      }

      if (next.start > index) {
        spans.add(pw.TextSpan(
            text: value.substring(index, next.start), style: style));
      }

      final end = value.indexOf(next.close, next.start + 1);
      if (end == -1) {
        spans.add(pw.TextSpan(text: value.substring(next.start), style: style));
        break;
      }

      final token = value.substring(next.start, end + 1);
      final color = _bracketColor(next.open, token);
      spans.add(
        pw.TextSpan(
          text: token,
          style: style.copyWith(
            color: color,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      );
      index = end + 1;
    }

    return pw.RichText(text: pw.TextSpan(children: spans, style: style));
  }

  static ({int start, String open, String close})? _nextBracket(
    String value,
    int from,
  ) {
    final candidates = <({int start, String open, String close})>[
      (start: value.indexOf('[', from), open: '[', close: ']'),
      (start: value.indexOf('(', from), open: '(', close: ')'),
      (start: value.indexOf('{', from), open: '{', close: '}'),
    ].where((item) => item.start >= 0).toList();
    if (candidates.isEmpty) return null;
    candidates.sort((a, b) => a.start.compareTo(b.start));
    return candidates.first;
  }

  static PdfColor _bracketColor(String open, String token) {
    if (open == '(') return PdfColor.fromHex('#0F766E');
    if (open == '{') return PdfColor.fromHex('#EA580C');
    return PdfColor.fromHex('#2563EB');
  }

  static pw.Widget _sectionBox({
    required String title,
    required String color,
    required String border,
    required pw.Widget child,
  }) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex(color),
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(color: PdfColor.fromHex(border)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _sectionTitle(title),
          pw.SizedBox(height: 8),
          child,
        ],
      ),
    );
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        fontSize: 13,
        fontWeight: pw.FontWeight.bold,
        color: PdfColor.fromHex('#172033'),
      ),
    );
  }

  static pw.Widget _smallLabel(String label, {String color = '#2563EB'}) {
    return pw.Text(
      label,
      style: pw.TextStyle(
        fontSize: 8.5,
        fontWeight: pw.FontWeight.bold,
        color: PdfColor.fromHex(color),
      ),
    );
  }

  static pw.Widget _emptyText(String value) {
    return pw.Text(
      value,
      style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
    );
  }

  static String _filename(FinalTouchReport report) {
    final parts = [
      'final_touch',
      if (report.textbookFolder.trim().isNotEmpty) report.textbookFolder,
      if (report.unitFolder.trim().isNotEmpty) report.unitFolder,
      if (report.textbookFolder.trim().isEmpty &&
          report.unitFolder.trim().isEmpty &&
          report.source.trim().isNotEmpty)
        report.source,
      _dateForFilename(),
    ];
    return '${parts.map(_safePart).where((part) => part.isNotEmpty).join('_')}.pdf';
  }

  static String _safePart(String value) {
    return value
        .replaceAll(RegExp(r'[\\/:*?"<>|]'), '')
        .replaceAll(RegExp(r'\s+'), '')
        .trim();
  }

  static String _dateForFilename() {
    final now = DateTime.now();
    return '${now.year}-${now.month.toString().padLeft(2, '0')}-'
        '${now.day.toString().padLeft(2, '0')}';
  }

  static String _formatDate(String value) {
    final parsed = DateTime.tryParse(value);
    final date = parsed?.toLocal() ?? DateTime.now();
    return '${date.year}.${date.month.toString().padLeft(2, '0')}.'
        '${date.day.toString().padLeft(2, '0')}';
  }
}
