import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/integrated_report.dart';

class IntegratedReportPdfGenerator {
  static Future<void> previewOrPrint(IntegratedReport report) async {
    final bytes = await build(report);
    await Printing.layoutPdf(
      name: 'integrated_learning_report.pdf',
      onLayout: (_) async => bytes,
    );
  }

  static Future<Uint8List> build(IntegratedReport report) async {
    final fontData = await rootBundle.load(
      'assets/fonts/Noto_Sans_KR/NotoSansKR-VariableFont_wght.ttf',
    );
    final notoSans = pw.Font.ttf(fontData);
    final doc = pw.Document(
      theme: pw.ThemeData.withFont(
        base: notoSans,
        bold: notoSans,
      ),
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header(),
          pw.SizedBox(height: 18),
          _overallSummary(report),
          pw.SizedBox(height: 16),
          _trackComparison(report),
          pw.SizedBox(height: 16),
          _commonWeakBox(report),
          pw.SizedBox(height: 16),
          _recommendationBox(report),
          pw.SizedBox(height: 16),
          _recentResultsTable(
            title: '최근 내신 결과',
            emptyText: '아직 표시할 내신 결과가 없습니다.',
            items: report.recentProblemSetResults,
          ),
          pw.SizedBox(height: 16),
          _recentResultsTable(
            title: '최근 모의고사 결과',
            emptyText: '아직 표시할 모의고사 결과가 없습니다.',
            items: report.recentMockExamResults,
          ),
          pw.SizedBox(height: 24),
          pw.Divider(color: PdfColors.grey300),
          pw.Text(
            'Generated by 영어문제제작 시스템 / messimomo',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _header() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          '통합 학습 리포트',
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#111827'),
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          '내신 대비와 모의고사 대비 결과를 함께 확인해 보세요.',
          style: const pw.TextStyle(
            fontSize: 11,
            color: PdfColors.grey700,
          ),
        ),
      ],
    );
  }

  static pw.Widget _overallSummary(IntegratedReport report) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#EFF6FF'),
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: PdfColor.fromHex('#BFDBFE')),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            flex: 2,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  '전체 평균',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#1E40AF'),
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  '${_score(report.overallAverageScore)}점',
                  style: pw.TextStyle(
                    fontSize: 34,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#2563EB'),
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(width: 14),
          pw.Expanded(
            flex: 4,
            child: pw.Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _metricPill('내신 응시', '${report.problemSetAttemptCount}회'),
                _metricPill('모의고사 응시', '${report.mockExamAttemptCount}회'),
                _metricPill(
                  '내신 평균',
                  '${_score(report.problemSetAverageScore)}점',
                ),
                _metricPill(
                  '모의고사 평균',
                  '${_score(report.mockExamAverageScore)}점',
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _metricPill(String label, String value) {
    return pw.Container(
      width: 118,
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColor.fromHex('#DBEAFE')),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#111827'),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _trackComparison(IntegratedReport report) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: _trackBox(
            title: '내신 대비',
            attemptCount: report.problemSetAttemptCount,
            averageScore: report.problemSetAverageScore,
            latestScore: report.latestProblemSetScore,
            weakTypes: report.problemSetWeakTypes,
            colorHex: '#7C3AED',
          ),
        ),
        pw.SizedBox(width: 12),
        pw.Expanded(
          child: _trackBox(
            title: '모의고사 대비',
            attemptCount: report.mockExamAttemptCount,
            averageScore: report.mockExamAverageScore,
            latestScore: report.latestMockExamScore,
            weakTypes: report.mockExamWeakTypes,
            colorHex: '#2563EB',
          ),
        ),
      ],
    );
  }

  static pw.Widget _trackBox({
    required String title,
    required int attemptCount,
    required double averageScore,
    required int? latestScore,
    required List<String> weakTypes,
    required String colorHex,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: PdfColor.fromHex('#E5E7EB')),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex(colorHex),
            ),
          ),
          pw.SizedBox(height: 10),
          _lineMetric('응시', '$attemptCount회'),
          _lineMetric('평균', '${_score(averageScore)}점'),
          _lineMetric('최근', latestScore == null ? '-' : '$latestScore점'),
          pw.SizedBox(height: 8),
          pw.Text(
            '약점: ${_joinOrNone(weakTypes)}',
            style: const pw.TextStyle(
              fontSize: 10,
              height: 1.4,
              color: PdfColors.grey800,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _lineMetric(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 5),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromHex('#111827'),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _commonWeakBox(IntegratedReport report) {
    final text = report.commonWeakTypes.isEmpty
        ? '공통으로 반복되는 약점 유형은 아직 없습니다.'
        : report.commonWeakTypes.join(', ');
    final hasWeak = report.commonWeakTypes.isNotEmpty;
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color:
            hasWeak ? PdfColor.fromHex('#FFF7ED') : PdfColor.fromHex('#F0FDF4'),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Text(
        '공통 약점: $text',
        style: pw.TextStyle(
          fontSize: 11,
          fontWeight: pw.FontWeight.bold,
          color: hasWeak
              ? PdfColor.fromHex('#C2410C')
              : PdfColor.fromHex('#16A34A'),
        ),
      ),
    );
  }

  static pw.Widget _recommendationBox(IntegratedReport report) {
    final items = report.recommendations.isEmpty
        ? ['누적 결과가 더 쌓이면 맞춤 추천이 제공됩니다.']
        : report.recommendations;

    return _section(
      '추천 학습 방향',
      pw.Container(
        width: double.infinity,
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromHex('#F8FAFC'),
          borderRadius: pw.BorderRadius.circular(10),
          border: pw.Border.all(color: PdfColor.fromHex('#E2E8F0')),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: items
              .map(
                (item) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 6),
                  child: pw.Text(
                    '- $item',
                    style: const pw.TextStyle(
                      fontSize: 10,
                      height: 1.45,
                      color: PdfColors.grey800,
                    ),
                  ),
                ),
              )
              .toList(),
        ),
      ),
    );
  }

  static pw.Widget _recentResultsTable({
    required String title,
    required String emptyText,
    required List<RecentResultItem> items,
  }) {
    if (items.isEmpty) {
      return _section(
        title,
        pw.Text(
          emptyText,
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      );
    }

    return _section(
      title,
      pw.TableHelper.fromTextArray(
        headers: ['제목', '응시일', '점수', '정답'],
        data: items
            .map(
              (item) => [
                item.title,
                _formatDate(item.submittedAt),
                '${item.score}점',
                '${item.correctCount}/${item.totalCount}',
              ],
            )
            .toList(),
        headerStyle: pw.TextStyle(
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
          color: PdfColor.fromHex('#111827'),
        ),
        cellStyle: const pw.TextStyle(fontSize: 8, color: PdfColors.grey800),
        headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#EFF6FF')),
        border: pw.TableBorder.all(color: PdfColor.fromHex('#E2E8F0')),
        cellAlignment: pw.Alignment.centerLeft,
        cellAlignments: {
          1: pw.Alignment.center,
          2: pw.Alignment.center,
          3: pw.Alignment.center,
        },
      ),
    );
  }

  static pw.Widget _section(String title, pw.Widget child) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 13,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#111827'),
          ),
        ),
        pw.SizedBox(height: 8),
        child,
      ],
    );
  }

  static String _joinOrNone(List<String> items) {
    if (items.isEmpty) return '뚜렷한 약점 없음';
    return items.join(', ');
  }

  static String _score(num value) {
    final score = value.toDouble();
    return score == score.roundToDouble()
        ? score.round().toString()
        : score.toStringAsFixed(1);
  }

  static String _formatDate(String? value) {
    if (value == null || value.isEmpty) return '-';
    final parsed = DateTime.tryParse(value);
    if (parsed == null) return value.split('T').first;
    final local = parsed.toLocal();
    return '${local.year}.${local.month.toString().padLeft(2, '0')}.'
        '${local.day.toString().padLeft(2, '0')}';
  }
}
