import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/mock_exam_result_report.dart';

class MockExamPdfGenerator {
  static Future<void> previewOrPrint(
    MockExamResultReport report, {
    List<MockExamWrongQuestionPdfItem> wrongQuestions = const [],
  }) async {
    final bytes = await build(
      report,
      wrongQuestions: wrongQuestions,
    );
    await Printing.layoutPdf(
      name: _safeFilename('${report.examTitle}_result.pdf'),
      onLayout: (_) async => bytes,
    );
  }

  static Future<Uint8List> build(
    MockExamResultReport report, {
    List<MockExamWrongQuestionPdfItem> wrongQuestions = const [],
  }) async {
    final fontData = await rootBundle.load(
      'assets/fonts/Noto_Sans_KR/NotoSansKR-VariableFont_wght.ttf',
    );
    final notoSans = pw.Font.ttf(fontData);
    final doc = pw.Document(
      theme: pw.ThemeData.withFont(
        base: notoSans,
        bold: notoSans,
      ),
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _header(report),
          pw.SizedBox(height: 18),
          _scoreBox(report),
          pw.SizedBox(height: 16),
          _weakBox(report),
          pw.SizedBox(height: 16),
          _typeTable(report),
          pw.SizedBox(height: 16),
          _questionGrid(report),
          if (wrongQuestions.isNotEmpty) ...[
            pw.SizedBox(height: 18),
            _wrongQuestionTable(wrongQuestions),
          ],
          pw.SizedBox(height: 24),
          pw.Divider(color: PdfColors.grey300),
          pw.Text(
            'Generated by 영어문제제작 시스템 / messimomo',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _header(MockExamResultReport report) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          '모의고사 결과지',
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#172033'),
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          report.examTitle,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#2563EB'),
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '응시일: ${_formatDateTime(report.submittedAt)}',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
      ],
    );
  }

  static pw.Widget _scoreBox(MockExamResultReport report) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#EFF6FF'),
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: PdfColor.fromHex('#BFDBFE')),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            flex: 2,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  '${report.score}점',
                  style: pw.TextStyle(
                    fontSize: 34,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#2563EB'),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  '${report.correctCount} / ${report.totalCount} 정답 · ${_score(report.percent)}%',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#172033'),
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(width: 14),
          pw.Expanded(
            flex: 3,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  '학습 코멘트',
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#172033'),
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  report.scoreComment,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    height: 1.45,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text(
                  report.recommendation,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    height: 1.45,
                    color: PdfColors.grey800,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _weakBox(MockExamResultReport report) {
    final text = report.weakTypes.isEmpty
        ? '뚜렷한 약점 유형이 없습니다.'
        : report.weakTypes.join(', ');
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: report.weakTypes.isEmpty
            ? PdfColor.fromHex('#F0FDF4')
            : PdfColor.fromHex('#FFF7ED'),
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Text(
        '약점 유형: $text',
        style: pw.TextStyle(
          fontSize: 11,
          fontWeight: pw.FontWeight.bold,
          color: report.weakTypes.isEmpty
              ? PdfColor.fromHex('#16A34A')
              : PdfColor.fromHex('#C2410C'),
        ),
      ),
    );
  }

  static pw.Widget _typeTable(MockExamResultReport report) {
    final rows = report.typeSummary.values
        .map(
          (item) => [
            item.label,
            '${item.correct}',
            '${item.total}',
            '${_score(item.rate)}%',
          ],
        )
        .toList();
    return _section(
      '유형별 분석',
      pw.TableHelper.fromTextArray(
        headers: ['유형', '정답 수', '전체', '정답률'],
        data: rows,
        headerStyle: pw.TextStyle(
          fontSize: 10,
          fontWeight: pw.FontWeight.bold,
          color: PdfColor.fromHex('#172033'),
        ),
        cellStyle: const pw.TextStyle(fontSize: 9, color: PdfColors.grey800),
        headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#EFF6FF')),
        border: pw.TableBorder.all(color: PdfColor.fromHex('#E2E8F0')),
        cellAlignment: pw.Alignment.centerLeft,
        cellAlignments: {
          1: pw.Alignment.center,
          2: pw.Alignment.center,
          3: pw.Alignment.center,
        },
      ),
    );
  }

  static pw.Widget _questionGrid(MockExamResultReport report) {
    return _section(
      '문항별 O/X 요약',
      pw.Wrap(
        spacing: 6,
        runSpacing: 6,
        children: report.questionResults.map((item) {
          final color = item.correct
              ? PdfColor.fromHex('#16A34A')
              : PdfColor.fromHex('#DC2626');
          final bg = item.correct
              ? PdfColor.fromHex('#F0FDF4')
              : PdfColor.fromHex('#FEF2F2');
          return pw.Container(
            width: 42,
            padding: const pw.EdgeInsets.symmetric(vertical: 6),
            decoration: pw.BoxDecoration(
              color: bg,
              borderRadius: pw.BorderRadius.circular(8),
              border: pw.Border.all(color: color),
            ),
            child: pw.Column(
              children: [
                pw.Text(
                  '${item.number}',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#172033'),
                  ),
                ),
                pw.Text(
                  item.correct ? 'O' : 'X',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: color,
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  static pw.Widget _wrongQuestionTable(
    List<MockExamWrongQuestionPdfItem> wrongQuestions,
  ) {
    final rows = wrongQuestions
        .map(
          (item) => [
            '${item.number}',
            item.typeLabel,
            item.selectedAnswer,
            item.correctAnswer,
            item.explanation.isEmpty ? '해설 없음' : item.explanation,
          ],
        )
        .toList();
    return _section(
      '오답 상세',
      pw.TableHelper.fromTextArray(
        headers: ['번호', '유형', '내 답', '정답', '해설'],
        data: rows,
        headerStyle: pw.TextStyle(
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
          color: PdfColor.fromHex('#172033'),
        ),
        cellStyle: const pw.TextStyle(fontSize: 8, color: PdfColors.grey800),
        headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#FFF7ED')),
        border: pw.TableBorder.all(color: PdfColor.fromHex('#E2E8F0')),
        cellAlignment: pw.Alignment.centerLeft,
        cellAlignments: {
          0: pw.Alignment.center,
          2: pw.Alignment.center,
          3: pw.Alignment.center,
        },
      ),
    );
  }

  static pw.Widget _section(String title, pw.Widget child) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 13,
            fontWeight: pw.FontWeight.bold,
            color: PdfColor.fromHex('#172033'),
          ),
        ),
        pw.SizedBox(height: 8),
        child,
      ],
    );
  }

  static String _safeFilename(String value) {
    final cleaned = value.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_');
    return cleaned.isEmpty ? 'mock_exam_result.pdf' : cleaned;
  }

  static String _score(double value) {
    return value == value.roundToDouble()
        ? value.toInt().toString()
        : value.toStringAsFixed(1);
  }

  static String _formatDateTime(String value) {
    final parsed = DateTime.tryParse(value);
    if (parsed == null) return '-';
    final local = parsed.toLocal();
    return '${local.year}.${local.month.toString().padLeft(2, '0')}.'
        '${local.day.toString().padLeft(2, '0')} '
        '${local.hour.toString().padLeft(2, '0')}:'
        '${local.minute.toString().padLeft(2, '0')}';
  }
}

class MockExamWrongQuestionPdfItem {
  const MockExamWrongQuestionPdfItem({
    required this.number,
    required this.typeLabel,
    required this.selectedAnswer,
    required this.correctAnswer,
    required this.explanation,
  });

  final int number;
  final String typeLabel;
  final String selectedAnswer;
  final String correctAnswer;
  final String explanation;
}
